# Generated by Django 4.1.7 on 2024-04-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SparkleMart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
