# Generated by Django 4.1.7 on 2024-04-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SparkleMart', '0003_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.PositiveSmallIntegerField(default=10),
            preserve_default=False,
        ),
    ]
