# Generated by Django 4.1.7 on 2024-04-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SparkleMart', '0004_news_alter_contact_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
