# Generated by Django 4.1.7 on 2024-04-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SparkleMart', '0005_delete_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(default=19),
            preserve_default=False,
        ),
    ]
