# Generated by Django 4.1.7 on 2024-04-27 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SparkleMart', '0007_purchase_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('discount', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.CreateModel(
            name='PromoUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SparkleMart.promo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
